### PR TITLE
change deprecated variable name

### PR DESCRIPTION
**Pull request by chozelinek**
Hi @wanthalf,
I'm trying to install InterText with PHP7.0. When I tried to create the database with the script `intertext.sql` using `mysql -p -u root < intertext.sql` I got the following error message:

> ERROR 1193 (HY000) at line 2: Unknown system variable 'storage_engine'

It seems that in the latest MySQL versions this variable is called 'default_store_engine'.

By declaring 'default_store_engine' instead of 'store_engine' the problem is solved.

Best!

### CODE REVIEW

**Comment by chozelinek** [comment]
I realized that also `lib_intertext.php` has to be modified.

**Comment by wanthalf** [comment]
Thanks a lot! (Also the whitespace... the code probably needs complete re-indentation as well..).

**Comment by chozelinek** [comment]
Sorry for the changes due to the automatic removal of trailing spaces done by my editor. I should have checked that before pushing and sending the pull request. Now, it is a bit difficult to check where was the meaningful bit. My bad ;-)

I hope the changes do not introduce some kind of backwards incompatibility.

**Comment by wanthalf** [comment]
No problem.

No deep backwards compatibility is guaranteed, anyway. MySQL >= 5.6 is highly recommended, because of support for full text search in InnoDB tables. Older versions of MySQL do only support fulltext-search in MyISAM tables, which do not support transactions, on the other hand. Maybe, full text search is not a necessary feature for most people, but running really obsolete software is not that smart either. And InnoDB in MySQL <5.0 is probably not the best idea generally.

**Pull request merged**
